# Generated by Django 6.0.4 on 2026-04-22 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_hi', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('construction', 'Construction'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('carpentry', 'Carpentry'), ('painting', 'Painting'), ('driving', 'Driving'), ('cooking', 'Cooking'), ('cleaning', 'Cleaning'), ('security', 'Security'), ('welding', 'Welding'), ('ac_tech', 'AC Technician'), ('tailoring', 'Tailoring'), ('other', 'Other')], max_length=30)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('daily', 'Daily Wage'), ('internship', 'Internship')], default='full_time', max_length=20)),
                ('experience_req', models.CharField(choices=[('fresher', 'Fresher (0 yrs)'), ('1_2', '1–2 Years'), ('3_5', '3–5 Years'), ('5_plus', '5+ Years'), ('10_plus', '10+ Years')], default='fresher', max_length=20)),
                ('skills_required', models.CharField(blank=True, help_text='Comma-separated skills', max_length=500)),
                ('description', models.TextField()),
                ('description_hi', models.TextField(blank=True)),
                ('location', models.CharField(max_length=200)),
                ('salary_min', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salary_max', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('openings', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'job')},
            },
        ),
    ]
