# Generated by Django 6.0.4 on 2026-04-22 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_enhance_review_system'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_reviewe_f0f3ae_idx',
            old_name='reviews_revi_reviewe_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_rating_2db6dd_idx',
            old_name='reviews_revi_rating_idx',
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, help_text='Detailed feedback'),
        ),
        migrations.AlterField(
            model_name='review',
            name='communication',
            field=models.PositiveSmallIntegerField(default=5, help_text='Communication skill', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Verified purchase/work'),
        ),
        migrations.AlterField(
            model_name='review',
            name='professionalism',
            field=models.PositiveSmallIntegerField(default=5, help_text='Professional behavior', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='punctuality',
            field=models.PositiveSmallIntegerField(default=5, help_text='On-time delivery', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='quality_rating',
            field=models.PositiveSmallIntegerField(default=5, help_text='Quality of work', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(5, '⭐⭐⭐⭐⭐ Excellent'), (4, '⭐⭐⭐⭐ Very Good'), (3, '⭐⭐⭐ Good'), (2, '⭐⭐ Fair'), (1, '⭐ Poor')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, help_text='Review title', max_length=200),
        ),
    ]
