# Generated by Django 6.0.4 on 2026-04-22 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(choices=[('plumber', 'Plumber'), ('electrician', 'Electrician'), ('carpenter', 'Carpenter'), ('painter', 'Painter'), ('driver', 'Driver'), ('cook', 'Cook'), ('security', 'Security Guard'), ('cleaner', 'Cleaner'), ('mason', 'Mason'), ('welder', 'Welder'), ('ac_technician', 'AC Technician'), ('tailor', 'Tailor'), ('other', 'Other')], default='other', max_length=50)),
                ('extra_skills', models.CharField(blank=True, help_text='Additional comma-separated skills', max_length=300)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('availability', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('total_jobs', models.PositiveIntegerField(default=0)),
                ('address', models.TextField(blank=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='worker_resumes/')),
                ('aadhar_verified', models.BooleanField(default=False)),
                ('portfolio_url', models.URLField(blank=True)),
                ('languages', models.CharField(blank=True, default='Hindi, English', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
