# Generated by Django 6.0.4 on 2026-04-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_add_location_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Worker location latitude', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Worker location longitude', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='working_radius_km',
            field=models.PositiveIntegerField(default=10, help_text='Working radius in kilometers'),
        ),
    ]
