# Generated by Django 6.0.4 on 2026-04-22 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_alter_workerprofile_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workerprofile',
            options={'ordering': ['-updated_at']},
        ),
    ]
